spring.datasource.url=jdbc:mysql://localhost:3306/NOOP_project
spring.datasource.username=root
spring.datasource.password=database99

spring.jpa.properties.hibernate.diselect= org.hibernate.dialect.MySQL5InnoDBDialect

spring.liquibase.change-log=db/master-changelog.xml

